// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: pb/blob.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Height uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	// Namespaces as raw 29-byte values
	Namespaces    [][]byte `protobuf:"bytes,2,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_pb_blob_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blob_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_pb_blob_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *GetAllRequest) GetNamespaces() [][]byte {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blobs         []*Blob                `protobuf:"bytes,1,rep,name=blobs,proto3" json:"blobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_pb_blob_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blob_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_pb_blob_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllResponse) GetBlobs() []*Blob {
	if x != nil {
		return x.Blobs
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Namespace     []byte                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Commitment    []byte                 `protobuf:"bytes,3,opt,name=commitment,proto3" json:"commitment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_pb_blob_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blob_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_pb_blob_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *GetRequest) GetNamespace() []byte {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *GetRequest) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blob          *Blob                  `protobuf:"bytes,1,opt,name=blob,proto3" json:"blob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_pb_blob_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blob_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_pb_blob_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetBlob() *Blob {
	if x != nil {
		return x.Blob
	}
	return nil
}

type GetProofRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Namespace     []byte                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Commitment    []byte                 `protobuf:"bytes,3,opt,name=commitment,proto3" json:"commitment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProofRequest) Reset() {
	*x = GetProofRequest{}
	mi := &file_pb_blob_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProofRequest) ProtoMessage() {}

func (x *GetProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blob_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProofRequest.ProtoReflect.Descriptor instead.
func (*GetProofRequest) Descriptor() ([]byte, []int) {
	return file_pb_blob_proto_rawDescGZIP(), []int{4}
}

func (x *GetProofRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *GetProofRequest) GetNamespace() []byte {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *GetProofRequest) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

type GetProofResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proof         *Proof                 `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProofResponse) Reset() {
	*x = GetProofResponse{}
	mi := &file_pb_blob_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProofResponse) ProtoMessage() {}

func (x *GetProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blob_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProofResponse.ProtoReflect.Descriptor instead.
func (*GetProofResponse) Descriptor() ([]byte, []int) {
	return file_pb_blob_proto_rawDescGZIP(), []int{5}
}

func (x *GetProofResponse) GetProof() *Proof {
	if x != nil {
		return x.Proof
	}
	return nil
}

type SubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blobs         []*Blob                `protobuf:"bytes,1,rep,name=blobs,proto3" json:"blobs,omitempty"`
	GasPrice      float64                `protobuf:"fixed64,2,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_pb_blob_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blob_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_pb_blob_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitRequest) GetBlobs() []*Blob {
	if x != nil {
		return x.Blobs
	}
	return nil
}

func (x *SubmitRequest) GetGasPrice() float64 {
	if x != nil {
		return x.GasPrice
	}
	return 0
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_pb_blob_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blob_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_pb_blob_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitResponse) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Blob represents a data blob in Celestia.
type Blob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     []byte                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Commitment    []byte                 `protobuf:"bytes,3,opt,name=commitment,proto3" json:"commitment,omitempty"`
	ShareVersion  uint32                 `protobuf:"varint,4,opt,name=share_version,json=shareVersion,proto3" json:"share_version,omitempty"`
	Index         uint64                 `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	Signer        []byte                 `protobuf:"bytes,6,opt,name=signer,proto3" json:"signer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blob) Reset() {
	*x = Blob{}
	mi := &file_pb_blob_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blob) ProtoMessage() {}

func (x *Blob) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blob_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blob.ProtoReflect.Descriptor instead.
func (*Blob) Descriptor() ([]byte, []int) {
	return file_pb_blob_proto_rawDescGZIP(), []int{8}
}

func (x *Blob) GetNamespace() []byte {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *Blob) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Blob) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *Blob) GetShareVersion() uint32 {
	if x != nil {
		return x.ShareVersion
	}
	return 0
}

func (x *Blob) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Blob) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

// Proof contains the NMT proof for blob inclusion.
type Proof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proofs        []*NMTProof            `protobuf:"bytes,1,rep,name=proofs,proto3" json:"proofs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proof) Reset() {
	*x = Proof{}
	mi := &file_pb_blob_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proof) ProtoMessage() {}

func (x *Proof) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blob_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proof.ProtoReflect.Descriptor instead.
func (*Proof) Descriptor() ([]byte, []int) {
	return file_pb_blob_proto_rawDescGZIP(), []int{9}
}

func (x *Proof) GetProofs() []*NMTProof {
	if x != nil {
		return x.Proofs
	}
	return nil
}

// NMTProof is the Namespace Merkle Tree proof.
type NMTProof struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Start                 int64                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End                   int64                  `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Nodes                 [][]byte               `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	LeafHash              []byte                 `protobuf:"bytes,4,opt,name=leaf_hash,json=leafHash,proto3" json:"leaf_hash,omitempty"`
	IsMaxNamespaceIgnored bool                   `protobuf:"varint,5,opt,name=is_max_namespace_ignored,json=isMaxNamespaceIgnored,proto3" json:"is_max_namespace_ignored,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *NMTProof) Reset() {
	*x = NMTProof{}
	mi := &file_pb_blob_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NMTProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NMTProof) ProtoMessage() {}

func (x *NMTProof) ProtoReflect() protoreflect.Message {
	mi := &file_pb_blob_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NMTProof.ProtoReflect.Descriptor instead.
func (*NMTProof) Descriptor() ([]byte, []int) {
	return file_pb_blob_proto_rawDescGZIP(), []int{10}
}

func (x *NMTProof) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *NMTProof) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *NMTProof) GetNodes() [][]byte {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *NMTProof) GetLeafHash() []byte {
	if x != nil {
		return x.LeafHash
	}
	return nil
}

func (x *NMTProof) GetIsMaxNamespaceIgnored() bool {
	if x != nil {
		return x.IsMaxNamespaceIgnored
	}
	return false
}

var File_pb_blob_proto protoreflect.FileDescriptor

const file_pb_blob_proto_rawDesc = "" +
	"\n" +
	"\rpb/blob.proto\x12\tgrpc.blob\"G\n" +
	"\rGetAllRequest\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x02 \x03(\fR\n" +
	"namespaces\"7\n" +
	"\x0eGetAllResponse\x12%\n" +
	"\x05blobs\x18\x01 \x03(\v2\x0f.grpc.blob.BlobR\x05blobs\"b\n" +
	"\n" +
	"GetRequest\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\fR\tnamespace\x12\x1e\n" +
	"\n" +
	"commitment\x18\x03 \x01(\fR\n" +
	"commitment\"2\n" +
	"\vGetResponse\x12#\n" +
	"\x04blob\x18\x01 \x01(\v2\x0f.grpc.blob.BlobR\x04blob\"g\n" +
	"\x0fGetProofRequest\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\fR\tnamespace\x12\x1e\n" +
	"\n" +
	"commitment\x18\x03 \x01(\fR\n" +
	"commitment\":\n" +
	"\x10GetProofResponse\x12&\n" +
	"\x05proof\x18\x01 \x01(\v2\x10.grpc.blob.ProofR\x05proof\"S\n" +
	"\rSubmitRequest\x12%\n" +
	"\x05blobs\x18\x01 \x03(\v2\x0f.grpc.blob.BlobR\x05blobs\x12\x1b\n" +
	"\tgas_price\x18\x02 \x01(\x01R\bgasPrice\"(\n" +
	"\x0eSubmitResponse\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\"\xab\x01\n" +
	"\x04Blob\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\fR\tnamespace\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1e\n" +
	"\n" +
	"commitment\x18\x03 \x01(\fR\n" +
	"commitment\x12#\n" +
	"\rshare_version\x18\x04 \x01(\rR\fshareVersion\x12\x14\n" +
	"\x05index\x18\x05 \x01(\x04R\x05index\x12\x16\n" +
	"\x06signer\x18\x06 \x01(\fR\x06signer\"4\n" +
	"\x05Proof\x12+\n" +
	"\x06proofs\x18\x01 \x03(\v2\x13.grpc.blob.NMTProofR\x06proofs\"\x9e\x01\n" +
	"\bNMTProof\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x03R\x03end\x12\x14\n" +
	"\x05nodes\x18\x03 \x03(\fR\x05nodes\x12\x1b\n" +
	"\tleaf_hash\x18\x04 \x01(\fR\bleafHash\x127\n" +
	"\x18is_max_namespace_ignored\x18\x05 \x01(\bR\x15isMaxNamespaceIgnored2\x86\x02\n" +
	"\vBlobService\x12=\n" +
	"\x06GetAll\x12\x18.grpc.blob.GetAllRequest\x1a\x19.grpc.blob.GetAllResponse\x124\n" +
	"\x03Get\x12\x15.grpc.blob.GetRequest\x1a\x16.grpc.blob.GetResponse\x12C\n" +
	"\bGetProof\x12\x1a.grpc.blob.GetProofRequest\x1a\x1b.grpc.blob.GetProofResponse\x12=\n" +
	"\x06Submit\x12\x18.grpc.blob.SubmitRequest\x1a\x19.grpc.blob.SubmitResponseB:Z8github.com/celestiaorg/celestia-node/nodebuilder/grpc/pbb\x06proto3"

var (
	file_pb_blob_proto_rawDescOnce sync.Once
	file_pb_blob_proto_rawDescData []byte
)

func file_pb_blob_proto_rawDescGZIP() []byte {
	file_pb_blob_proto_rawDescOnce.Do(func() {
		file_pb_blob_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_blob_proto_rawDesc), len(file_pb_blob_proto_rawDesc)))
	})
	return file_pb_blob_proto_rawDescData
}

var file_pb_blob_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pb_blob_proto_goTypes = []any{
	(*GetAllRequest)(nil),    // 0: grpc.blob.GetAllRequest
	(*GetAllResponse)(nil),   // 1: grpc.blob.GetAllResponse
	(*GetRequest)(nil),       // 2: grpc.blob.GetRequest
	(*GetResponse)(nil),      // 3: grpc.blob.GetResponse
	(*GetProofRequest)(nil),  // 4: grpc.blob.GetProofRequest
	(*GetProofResponse)(nil), // 5: grpc.blob.GetProofResponse
	(*SubmitRequest)(nil),    // 6: grpc.blob.SubmitRequest
	(*SubmitResponse)(nil),   // 7: grpc.blob.SubmitResponse
	(*Blob)(nil),             // 8: grpc.blob.Blob
	(*Proof)(nil),            // 9: grpc.blob.Proof
	(*NMTProof)(nil),         // 10: grpc.blob.NMTProof
}
var file_pb_blob_proto_depIdxs = []int32{
	8,  // 0: grpc.blob.GetAllResponse.blobs:type_name -> grpc.blob.Blob
	8,  // 1: grpc.blob.GetResponse.blob:type_name -> grpc.blob.Blob
	9,  // 2: grpc.blob.GetProofResponse.proof:type_name -> grpc.blob.Proof
	8,  // 3: grpc.blob.SubmitRequest.blobs:type_name -> grpc.blob.Blob
	10, // 4: grpc.blob.Proof.proofs:type_name -> grpc.blob.NMTProof
	0,  // 5: grpc.blob.BlobService.GetAll:input_type -> grpc.blob.GetAllRequest
	2,  // 6: grpc.blob.BlobService.Get:input_type -> grpc.blob.GetRequest
	4,  // 7: grpc.blob.BlobService.GetProof:input_type -> grpc.blob.GetProofRequest
	6,  // 8: grpc.blob.BlobService.Submit:input_type -> grpc.blob.SubmitRequest
	1,  // 9: grpc.blob.BlobService.GetAll:output_type -> grpc.blob.GetAllResponse
	3,  // 10: grpc.blob.BlobService.Get:output_type -> grpc.blob.GetResponse
	5,  // 11: grpc.blob.BlobService.GetProof:output_type -> grpc.blob.GetProofResponse
	7,  // 12: grpc.blob.BlobService.Submit:output_type -> grpc.blob.SubmitResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pb_blob_proto_init() }
func file_pb_blob_proto_init() {
	if File_pb_blob_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_blob_proto_rawDesc), len(file_pb_blob_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_blob_proto_goTypes,
		DependencyIndexes: file_pb_blob_proto_depIdxs,
		MessageInfos:      file_pb_blob_proto_msgTypes,
	}.Build()
	File_pb_blob_proto = out.File
	file_pb_blob_proto_goTypes = nil
	file_pb_blob_proto_depIdxs = nil
}
